### ISSUE TITLE
Semantic Compliance

### ISSUE THREAD

**Issue by 21xhipster** [cyberFund/cyber.fund#305]

**Comment by lomashuk** [comment]
- [ ] build sitemap.xml and robots.txt #275
- [ ] enable prerender.io #274, #57
- [ ] add schema.org for Portrait and Profiles #251
- [ ] add Title, Meta and Open Graph #289

**Comment by 21xhipster** [comment]
@lomashuk Хотелось бы понять, что из этого сделано, а что осталось сделать
