### ISSUE TITLE
Second Iteration Roadmap

### ISSUE THREAD

**Issue by Undeadlol1** [cyberFund/cyber.fund#439]
### Finish Responsive design

- [ ] mdl table font-size, padding and margin
- [ ] IndexPage
- [ ] FundsPage
- [ ] ProfilePage
- [ ] SystemPage
- [ ] RadarPage
- [ ] RatingPage

### IndexPage

- [ ] enable "attract investments" button

### SystemPage

- [ ] {SlowChart} can you make selections in upper chart?
- [ ] {SlowChart} fix button styles
- [ ] "Internal Economy" total capitalisation must be displayed at the top
- [ ] fix tabs not rendering content
- [ ] add "markets tab"
- [ ] move systems to new tab section
- [ ] {KeenChart} background-color: transparent
- [ ] {KeenChart} can we retrieve total page visits count?
- [ ] {KeenChart} fix responsivness

### ProfilePage

- [ ] {SystemsList, UsersList} rework to "top 5 links"
- [ ] {SystemsList, UsersList} add third tab and move components into it
- [ ] change order of elements on mobile. Tabs > profile info
- [ ] move account total to the top right of the card
- [ ] change accounts from cards to tables (or a single table?)
- [ ] fix chart styles

### RadarPage

- [ ] card headers teaxt-align: center

### FundsPage

- [ ] fix table responsivness

### ListingPage

- [ ] implement google form from dev branch to react

### Various

- [ ] {Search} add system image and shortname (ex. BTC)
- [ ] change all links to 'cyber-talks' to /listing
- [ ] fix website seo (add prerender?)
- [ ] fix steem and steem power calculation

**Comment by 21xhipster** [comment]
Segment.com и ивенты

**Comment by lomashuk** [comment]
Schema.org
Open Grapth
?

**Comment by 21xhipster** [comment]
@lomashuk ага
